// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Sausage Saucer

#ifndef _SAUSAGE_SAUCER_UI_H
#define _SAUSAGE_SAUCER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_sauceScreen.h"
#include "screens/ui_patternScreen.h"
#include "screens/ui_jobScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bg_png);    // assets/bg.png
LV_IMG_DECLARE(ui_img_thick_png);    // assets/thick.png
LV_IMG_DECLARE(ui_img_tick_png);    // assets/tick.png
LV_IMG_DECLARE(ui_img_line_png);    // assets/line.png
LV_IMG_DECLARE(ui_img_zigzag_png);    // assets/zigzag.png
LV_IMG_DECLARE(ui_img_double_png);    // assets/double.png
LV_IMG_DECLARE(ui_img_wave_png);    // assets/wave.png
LV_IMG_DECLARE(ui_img_loops_png);    // assets/loops.png

// FONTS
LV_FONT_DECLARE(ui_font_FugazOne24);
LV_FONT_DECLARE(ui_font_FugazOne30);
LV_FONT_DECLARE(ui_font_FugazOne36);
LV_FONT_DECLARE(ui_font_FugazOne48);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
