// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Sausage Saucer

#ifndef UI_JOBSCREEN_H
#define UI_JOBSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_jobScreen
extern void ui_jobScreen_screen_init(void);
extern void ui_jobScreen_screen_destroy(void);
extern lv_obj_t * ui_jobScreen;
extern lv_obj_t * ui_detailStatusLabel;
extern lv_obj_t * ui_statusLabel;
extern void ui_event_loadButtonLabel(lv_event_t * e);
extern lv_obj_t * ui_loadButtonLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

