// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Sausage Saucer

#include "ui.h"

lv_obj_t * ui_jobScreen;
lv_obj_t * ui_detailStatusLabel;
lv_obj_t * ui_statusLabel;
lv_obj_t * ui_loadButtonLabel;

// event funtions
void ui_event_loadButtonLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_sauceScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_sauceScreen_screen_init);
    }
}

// build funtions

void ui_jobScreen_screen_init(void)
{
    ui_jobScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_jobScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_img_src(ui_jobScreen, &ui_img_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_detailStatusLabel = lv_label_create(ui_jobScreen);
    lv_obj_set_width(ui_detailStatusLabel, 460);
    lv_obj_set_height(ui_detailStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_detailStatusLabel, 10);
    lv_obj_set_y(ui_detailStatusLabel, 60);
    lv_label_set_text(ui_detailStatusLabel,
                      "The user info and status of the machine goes here. Wrapping text appears to work - yay!");
    lv_obj_clear_flag(ui_detailStatusLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_detailStatusLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_detailStatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_detailStatusLabel, &ui_font_FugazOne30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusLabel = lv_label_create(ui_jobScreen);
    lv_obj_set_width(ui_statusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_statusLabel, 10);
    lv_obj_set_y(ui_statusLabel, 10);
    lv_label_set_text(ui_statusLabel, "Working...");
    lv_obj_clear_flag(ui_statusLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_statusLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_statusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_statusLabel, &ui_font_FugazOne36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loadButtonLabel = lv_label_create(ui_jobScreen);
    lv_obj_set_width(ui_loadButtonLabel, 460);
    lv_obj_set_height(ui_loadButtonLabel, 26);
    lv_obj_set_x(ui_loadButtonLabel, 1);
    lv_obj_set_y(ui_loadButtonLabel, -10);
    lv_obj_set_align(ui_loadButtonLabel, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_loadButtonLabel, "Load another sausage?");
    lv_obj_add_flag(ui_loadButtonLabel, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_loadButtonLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_loadButtonLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_loadButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_loadButtonLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_loadButtonLabel, &ui_font_FugazOne24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_loadButtonLabel, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_loadButtonLabel, lv_color_hex(0x0099FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loadButtonLabel, 127, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_loadButtonLabel, ui_event_loadButtonLabel, LV_EVENT_ALL, NULL);

}

void ui_jobScreen_screen_destroy(void)
{
    if(ui_jobScreen) lv_obj_del(ui_jobScreen);

    // NULL screen variables
    ui_jobScreen = NULL;
    ui_detailStatusLabel = NULL;
    ui_statusLabel = NULL;
    ui_loadButtonLabel = NULL;

}
