// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Sausage Saucer

#include "ui.h"

lv_obj_t * ui_patternScreen;
lv_obj_t * ui_patternTitleLabel;
lv_obj_t * ui_skipLabel;
lv_obj_t * ui_thickButton;
lv_obj_t * ui_lineButton;
lv_obj_t * ui_zigzagButton;
lv_obj_t * ui_doubleButton;
lv_obj_t * ui_waveButton;
lv_obj_t * ui_loopsButton;
lv_obj_t * ui_infoLabel;

// event funtions
void ui_event_skipLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_jobScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_jobScreen_screen_init);
    }
}

// build funtions

void ui_patternScreen_screen_init(void)
{
    ui_patternScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_patternScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_img_src(ui_patternScreen, &ui_img_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_patternTitleLabel = lv_label_create(ui_patternScreen);
    lv_obj_set_width(ui_patternTitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_patternTitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_patternTitleLabel, 10);
    lv_obj_set_y(ui_patternTitleLabel, 10);
    lv_label_set_text(ui_patternTitleLabel, "Pattern:");
    lv_obj_clear_flag(ui_patternTitleLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_patternTitleLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_patternTitleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_patternTitleLabel, &ui_font_FugazOne36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_skipLabel = lv_label_create(ui_patternScreen);
    lv_obj_set_width(ui_skipLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_skipLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_skipLabel, -10);
    lv_obj_set_y(ui_skipLabel, 0);
    lv_obj_set_align(ui_skipLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_skipLabel, "Tap this text to begin!");
    lv_obj_add_flag(ui_skipLabel, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_skipLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_skipLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_skipLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_skipLabel, &ui_font_FugazOne30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_thickButton = lv_imgbtn_create(ui_patternScreen);
    lv_imgbtn_set_src(ui_thickButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_thick_png, NULL);
    lv_imgbtn_set_src(ui_thickButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_thick_png, NULL);
    lv_imgbtn_set_src(ui_thickButton, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_tick_png, NULL);
    lv_imgbtn_set_src(ui_thickButton, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_tick_png, NULL);
    lv_obj_set_width(ui_thickButton, 100);
    lv_obj_set_height(ui_thickButton, 100);
    lv_obj_set_x(ui_thickButton, 0);
    lv_obj_set_y(ui_thickButton, -55);
    lv_obj_set_align(ui_thickButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_thickButton, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_thickButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_lineButton = lv_imgbtn_create(ui_patternScreen);
    lv_imgbtn_set_src(ui_lineButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_line_png, NULL);
    lv_imgbtn_set_src(ui_lineButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_line_png, NULL);
    lv_imgbtn_set_src(ui_lineButton, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_tick_png, NULL);
    lv_imgbtn_set_src(ui_lineButton, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_tick_png, NULL);
    lv_obj_set_width(ui_lineButton, 100);
    lv_obj_set_height(ui_lineButton, 100);
    lv_obj_set_x(ui_lineButton, -145);
    lv_obj_set_y(ui_lineButton, -55);
    lv_obj_set_align(ui_lineButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lineButton, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_lineButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_zigzagButton = lv_imgbtn_create(ui_patternScreen);
    lv_imgbtn_set_src(ui_zigzagButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_zigzag_png, NULL);
    lv_imgbtn_set_src(ui_zigzagButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_zigzag_png, NULL);
    lv_imgbtn_set_src(ui_zigzagButton, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_tick_png, NULL);
    lv_imgbtn_set_src(ui_zigzagButton, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_tick_png, NULL);
    lv_obj_set_width(ui_zigzagButton, 100);
    lv_obj_set_height(ui_zigzagButton, 100);
    lv_obj_set_x(ui_zigzagButton, 145);
    lv_obj_set_y(ui_zigzagButton, -55);
    lv_obj_set_align(ui_zigzagButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zigzagButton, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_zigzagButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_doubleButton = lv_imgbtn_create(ui_patternScreen);
    lv_imgbtn_set_src(ui_doubleButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_double_png, NULL);
    lv_imgbtn_set_src(ui_doubleButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_double_png, NULL);
    lv_imgbtn_set_src(ui_doubleButton, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_tick_png, NULL);
    lv_imgbtn_set_src(ui_doubleButton, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_tick_png, NULL);
    lv_obj_set_width(ui_doubleButton, 100);
    lv_obj_set_height(ui_doubleButton, 100);
    lv_obj_set_x(ui_doubleButton, -145);
    lv_obj_set_y(ui_doubleButton, 55);
    lv_obj_set_align(ui_doubleButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_doubleButton, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_doubleButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_waveButton = lv_imgbtn_create(ui_patternScreen);
    lv_imgbtn_set_src(ui_waveButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_wave_png, NULL);
    lv_imgbtn_set_src(ui_waveButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_wave_png, NULL);
    lv_imgbtn_set_src(ui_waveButton, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_tick_png, NULL);
    lv_imgbtn_set_src(ui_waveButton, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_tick_png, NULL);
    lv_obj_set_width(ui_waveButton, 100);
    lv_obj_set_height(ui_waveButton, 100);
    lv_obj_set_x(ui_waveButton, 0);
    lv_obj_set_y(ui_waveButton, 55);
    lv_obj_set_align(ui_waveButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_waveButton, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_waveButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_loopsButton = lv_imgbtn_create(ui_patternScreen);
    lv_imgbtn_set_src(ui_loopsButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_loops_png, NULL);
    lv_imgbtn_set_src(ui_loopsButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_loops_png, NULL);
    lv_imgbtn_set_src(ui_loopsButton, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_tick_png, NULL);
    lv_imgbtn_set_src(ui_loopsButton, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_tick_png, NULL);
    lv_obj_set_width(ui_loopsButton, 100);
    lv_obj_set_height(ui_loopsButton, 100);
    lv_obj_set_x(ui_loopsButton, 145);
    lv_obj_set_y(ui_loopsButton, 55);
    lv_obj_set_align(ui_loopsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loopsButton, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_loopsButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_infoLabel = lv_label_create(ui_patternScreen);
    lv_obj_set_width(ui_infoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_infoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_infoLabel, -10);
    lv_obj_set_y(ui_infoLabel, 10);
    lv_obj_set_align(ui_infoLabel, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_infoLabel, "Press START to run.\nDefault is Line if none are selected.");
    lv_obj_clear_flag(ui_infoLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_infoLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_infoLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_infoLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_infoLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_skipLabel, ui_event_skipLabel, LV_EVENT_ALL, NULL);

}

void ui_patternScreen_screen_destroy(void)
{
    if(ui_patternScreen) lv_obj_del(ui_patternScreen);

    // NULL screen variables
    ui_patternScreen = NULL;
    ui_patternTitleLabel = NULL;
    ui_skipLabel = NULL;
    ui_thickButton = NULL;
    ui_lineButton = NULL;
    ui_zigzagButton = NULL;
    ui_doubleButton = NULL;
    ui_waveButton = NULL;
    ui_loopsButton = NULL;
    ui_infoLabel = NULL;

}
