// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Sausage Saucer

#ifndef UI_PATTERNSCREEN_H
#define UI_PATTERNSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_patternScreen
extern void ui_patternScreen_screen_init(void);
extern void ui_patternScreen_screen_destroy(void);
extern lv_obj_t * ui_patternScreen;
extern lv_obj_t * ui_patternTitleLabel;
extern void ui_event_skipLabel(lv_event_t * e);
extern lv_obj_t * ui_skipLabel;
extern lv_obj_t * ui_thickButton;
extern lv_obj_t * ui_lineButton;
extern lv_obj_t * ui_zigzagButton;
extern lv_obj_t * ui_doubleButton;
extern lv_obj_t * ui_waveButton;
extern lv_obj_t * ui_loopsButton;
extern lv_obj_t * ui_infoLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

