// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Sausage Saucer

#ifndef UI_SAUCESCREEN_H
#define UI_SAUCESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_sauceScreen
extern void ui_sauceScreen_screen_init(void);
extern void ui_sauceScreen_screen_destroy(void);
extern lv_obj_t * ui_sauceScreen;
extern lv_obj_t * ui_selectTitleLabel;
extern void ui_event_proceedInfoLabel(lv_event_t * e);
extern lv_obj_t * ui_proceedInfoLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

