// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Sausage Saucer

#include "ui.h"

lv_obj_t * ui_sauceScreen;
lv_obj_t * ui_selectTitleLabel;
lv_obj_t * ui_proceedInfoLabel;

// event funtions
void ui_event_proceedInfoLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_patternScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_patternScreen_screen_init);
    }
}

// build funtions

void ui_sauceScreen_screen_init(void)
{
    ui_sauceScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_sauceScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_img_src(ui_sauceScreen, &ui_img_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_selectTitleLabel = lv_label_create(ui_sauceScreen);
    lv_obj_set_width(ui_selectTitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_selectTitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_selectTitleLabel, 0);
    lv_obj_set_y(ui_selectTitleLabel, -20);
    lv_obj_set_align(ui_selectTitleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_selectTitleLabel, "Select your Sauces:");
    lv_obj_clear_flag(ui_selectTitleLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_selectTitleLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_selectTitleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_selectTitleLabel, &ui_font_FugazOne48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_proceedInfoLabel = lv_label_create(ui_sauceScreen);
    lv_obj_set_width(ui_proceedInfoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_proceedInfoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_proceedInfoLabel, 0);
    lv_obj_set_y(ui_proceedInfoLabel, 30);
    lv_obj_set_align(ui_proceedInfoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_proceedInfoLabel, "Press START to proceed");
    lv_obj_add_flag(ui_proceedInfoLabel, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_proceedInfoLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_proceedInfoLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_proceedInfoLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_proceedInfoLabel, &ui_font_FugazOne36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_proceedInfoLabel, ui_event_proceedInfoLabel, LV_EVENT_ALL, NULL);

}

void ui_sauceScreen_screen_destroy(void)
{
    if(ui_sauceScreen) lv_obj_del(ui_sauceScreen);

    // NULL screen variables
    ui_sauceScreen = NULL;
    ui_selectTitleLabel = NULL;
    ui_proceedInfoLabel = NULL;

}
